document.writeln("    <footer class=\'section section-primary\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("          <div class=\'col-sm-6\'>");
document.writeln("            <h1>WeiDingServer</h1>");
document.writeln("            <p>服主：魏丁");
document.writeln("              <br>網站設計：<a href=\'https://www.facebook.com/TPGoneTone\' target=\'_blank\'><font color=\'#ffffff\'>旋風之音</font></a>");
document.writeln("              <br>Copyright &copy; 2014-<script language=\'javascript\'>var Today=new Date(); document.write(Today.getFullYear() + \' ');</script><a href=\'/\'><font color=\'#ffffff\'>WeiDingServer</font></a> | All rights reserved.\</p>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-sm-6\'>");
document.writeln("            <p class=\'text-info text-right\'>");
document.writeln("              <br>");
document.writeln("              <br>");
document.writeln("            </p>");
document.writeln("            <div class=\'row\'>");
document.writeln("              <div class=\'col-md-12 hidden-lg hidden-md hidden-sm text-left\'>");
document.writeln("                <a href=\'https://www.facebook.com/groups/348950188620539\' target=\'_blank\'><i class=\'fa fa-3x fa-fw text-inverse fa-facebook-official\'></i></a>");
document.writeln("                <a href=\'/download/WeiServer.zip\'><i class=\'fa fa-3x fa-fw text-inverse fa-download\'></i></a>");
document.writeln("                <a href=\'https://github.com/WeiDingServer/weidingserver.github.io\' target=\'_blank\'><i class=\'fa fa-3x fa-fw fa-github text-inverse\'></i></a>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'row\'>");
document.writeln("              <div class=\'col-md-12 hidden-xs text-right\'>");
document.writeln("                <a href=\'https://www.facebook.com/groups/348950188620539\' target=\'_blank\'><i class=\'fa fa-3x fa-fw text-inverse fa-facebook-official\'></i></a>");
document.writeln("                <a href=\'/download/WeiServer.zip\'><i class=\'fa fa-3x fa-fw text-inverse fa-download\'></i></a>");
document.writeln("                <a href=\'https://github.com/WeiDingServer/weidingserver.github.io\' target=\'_blank\'><i class=\'fa fa-3x fa-fw fa-github text-inverse\'></i></a>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </footer>");