document.writeln("	<div class=\'navbar navbar-default navbar-static-top\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("          <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'#navbar-ex-collapse\'>");
document.writeln("            <span class=\'sr-only\'>導航欄</span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("          </button>");
document.writeln("          <a class=\'navbar-brand\' href=\'/\'><img border=\'0\' src=\'/images/logo.png\' height=\'35\'></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'navbar-ex-collapse\'>");
document.writeln("          <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("            <li>");
document.writeln("              <a href=\'/\'>首頁</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'/game\'>遊戲介紹</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'/plugins\'>插件介紹</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln('              <a onclick=\"window.alert' + "(\'未開放。\')" + '\">怪物介紹</a>');
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'/world\'>地圖介紹</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln('              <a onclick=\"window.alert' + "(\'未開放。\')" + '\">娛樂介紹</a>');
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'/rpgitem\'>物品專區</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'/picture\'>活動照片</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'/diary\'>遊戲日誌</a>");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");